import Head from 'next/head'
import {BsFillMoonStarsFill} from 'react-icons/bs'
import {AiFillTwitterCircle,AiFillLinkedin,AiFillGithub} from 'react-icons/ai'
import devsan from '../../public/image.jpg'
import Image from 'next/image'
import { useState } from 'react'

export default function Home() {
  const [darkMode,setDarkMode] = useState(false);

  return (
    <>
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Sahank29 Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-900" >
        <section className='h-screen'>
          <nav className='py-10 mb-12 flex justify-between'>
            <h1 className='text-xl font-burtons'>developedbySahan</h1>
            <ul className='flex items-center'>
              <li><BsFillMoonStarsFill onClick={()=>setDarkMode(!darkMode)} className='cursor-pointer-2xl'/></li>
              <li><a className='bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8' href="#">Resume</a></li>
            </ul>
          </nav>
          <div className='text-center p-5'>
            <h2 className='text-5xl py-3 text-teal-600 font-medium md:text-6xl'>Sahan C Poojari</h2>
            <h3 className='text-2xl py-2 md:text-3xl'>Software Developer Intern</h3>
            <p className='text-md py-5 leading-8 text-gray-800 md:text-xl max-w-lg mx-auto'>I use creative approach for problem solving.</p>
          </div>
          <div className='text-5xl flex justify-center gap-16 py-3 text-gray-600'>
            <a href= "https://twitter.com/sahank29">
              <AiFillTwitterCircle/>
            </a>
            <a href='https://www.linkedin.com/in/sahan-poojari-308b47214/'>
            <AiFillLinkedin/>
            </a>
            <a href='https://github.com/Sahank29'>
              <AiFillGithub/>
            </a>
            
          </div>
          <div className='relative mx-auto rounded-full w-80 h-80 mt-10 overflow-hidden md:h-96 md:w-96'>
            <Image src={devsan} layout='fill' objectFit='cover'/>
          </div>
        </section>
      </main>
      </div>
    </>
  );
}
