import Head from 'next/head'
import { BsFillMoonStarsFill,BsFillSunFill } from 'react-icons/bs'
import { AiFillTwitterCircle, AiFillLinkedin, AiFillGithub } from 'react-icons/ai'
import devsan from '../../public/image.jpg'
import Image from 'next/image'
import { useState, useEffect } from 'react'

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  return (
    <>
      <div className={`min-h-screen ${darkMode ? "dark" : "bg-white"}`}>
        <Head>
          <title>Sahank29 Portfolio</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className="bg-white px-7 md:px-7 lg:px-10 dark:bg-gray-900" >
          <section className='min-h-screen'>
            <nav className='py-5 flex justify-between md:py-7'>
              <h1 className='text-xl font-burtons dark:text-white'>developedbySahan</h1>
              <ul className='flex items-center'>
                <li>{darkMode ? 
                <BsFillSunFill onClick={() => {
                  setDarkMode(!darkMode)
                }} className='cursor-pointer-2xl dark:text-white'/>: 
                <BsFillMoonStarsFill onClick={() => {
                  setDarkMode(!darkMode)
                }} className='cursor-pointer-2xl' />
                }</li>
                {/* <li><a className='bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8' href="https://drive.google.com/file/d/1XoOcccc4fPPV1GlID2aG7w4zfrGqQkda/view?usp=sharing">Resume</a></li> */}
              </ul>
            </nav>
            <div className='relative mt-7 mx-auto rounded-full w-52 h-52 overflow-hidden md:h-54 md:w-54'>
              <Image src={devsan} layout='fill' objectFit='cover' />
            </div>
            <div className='text-center p-5'>
              <h2 className='text-4xl py-3 text-teal-600 font-medium md:text-6xl'>Sahan C Poojari</h2>
              <h3 className='text-2xl py-2 md:text-3xl dark:text-white'>Software Developer Intern</h3>
              <p className='text-md py-5 leading-8 text-gray-800 md:text-xl max-w-lg mx-auto dark:text-gray-200'>I use creative approach for problem solving.</p>
            </div>
            <div className='text-5xl flex justify-center gap-10 md:gap-16 py-3 text-gray-600 dark:text-white md:text-5xl lg:text-5xl'>
              <a href="https://twitter.com/sahank29">
                <AiFillTwitterCircle />
              </a>
              <a href='https://www.linkedin.com/in/sahan-poojari-308b47214/'>
                <AiFillLinkedin/>
              </a>
              <a href='https://github.com/Sahank29'>
              <AiFillGithub/>
            </a>
          </div>
        </section>
      </main>
      </div>
    </>
  );
}
